_wandb:
    value:
        cli_version: 0.23.1
        e:
            zvjjrttdd8xjtrt64pbzyykfnafim7yy:
                codePath: s2_organisation_and_version_control/exercise_files/M6_root/m6_project/src/m6_project/train.py
                codePathLocal: src/m6_project/train.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1081101176832"
                        used: "15135916032"
                email: s196050@dtu.dk
                executable: /home/mejse/miniconda3/envs/my_environment/bin/python
                git:
                    commit: e1c3943d7f9465dc916ea1c65eda4615605540f9
                    remote: https://github.com/MejseGK/dtu_mlops.git
                host: Teis-Laptop
                memory:
                    total: "7166164992"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/mejse/dtu/dtu_mlops/s2_organisation_and_version_control/exercise_files/M6_root/m6_project/src/m6_project/train.py
                python: CPython 3.11.14
                root: /home/mejse/dtu/dtu_mlops/s2_organisation_and_version_control/exercise_files/M6_root/m6_project
                startedAt: "2026-01-08T10:23:23.645024Z"
                writerId: zvjjrttdd8xjtrt64pbzyykfnafim7yy
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 16
            "4": 3.11.14
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 32
epochs:
    value: 5
lr:
    value: 0.001
